chat/urls.py
from django.urls import path
from .views import (
    chat,
)

app_name = 'chat'
urlpatterns = [
    path('', chat, name='chat'),
]

conocemibarrio/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from conocemibarrio import settings
from registration.views import send_push
from forum.views import notifications

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('registration.urls')),
    path('', include('neighborhood.urls')),
    path('forum/', include('forum.urls')),
    path('notifications/', notifications, name='notifications'),
    path('', include('pwa.urls')),
    path('', include('profile.urls')),
    path('chat/', include('chat.urls')),
    path('send_push', send_push),
    path('webpush/', include('webpush.urls')),
    path('sw.js', TemplateView.as_view(template_name='sw.js', content_type='application/x-javascript')),
    path('', include('realtime_map.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

neighborhood/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views import (createNeighborhood,
                    showNeighborhoodImages,
                    uploadNeighborhoodImage,
                    deleteNeighborhoodImage,
                    showPointsOfInterest,
                    editNeighborhood,
                    addPointOfInterest,
                    deletePointOfInterest,
                    editPointOfInterest,
                    deletePointOfInterestImage,
                    uploadPointOfInterestImage,
                    showPointOfInterestImages,
                    editNeighborhoodImage,
                    editPointOfInterestImage,
                    neighborhoodProfile,
                    pointOfInterestProfile,
                    )

app_name = 'neighborhood'

urlpatterns = [
    path('neighborhood/information/', createNeighborhood, name='createNeighborhood'),
    path('neighborhood/information/edit/', editNeighborhood, name='editNeighborhood'),
    path('neighborhood/images/', showNeighborhoodImages, name='showNeighborhoodImages'),
    path('neighborhood/images/sw.js', TemplateView.as_view(template_name='sw.js',
                                                           content_type='application/x-javascript')),
    path('neighborhood/<int:pk>/images/upload/', uploadNeighborhoodImage, name='uploadNeighborhoodImage'),
    path('neighborhood/<int:pk>/images/sw.js', TemplateView.as_view(template_name='sw.js',
                                                                    content_type='application/x-javascript')),
    path('neighborhood/image/<int:pk>/delete/', deleteNeighborhoodImage, name='deleteNeighborhoodImage'),
    path('neighborhood/image/<int:pk>/edit/', editNeighborhoodImage, name='editNeighborhoodImage'),
    path('neighborhood/<int:pk>/points_of_interest/add/', addPointOfInterest, name='addPointOfInterest'),
    path('neighborhood/point_of_interest/<int:pk>/edit/', editPointOfInterest, name='editPointOfInterest'),
    path('neighborhood/points_of_interest/', showPointsOfInterest, name='showPointsOfInterest'),
    path('neighborhood/point_of_interest/<int:pk>/delete/', deletePointOfInterest, name='deletePointOfInterest'),
    path('neighborhood/points_of_interest/image/<int:pk>/delete/',
         deletePointOfInterestImage, name='deletePointOfInterestImage'),
    path('neighborhood/point_of_interest/<int:pk>/image/upload/',
         uploadPointOfInterestImage, name='uploadPointOfInterestImage'),

    path('neighborhood/points_of_interest/image/<int:pk>/edit/',
         editPointOfInterestImage, name='editPointOfInterestImage'),

    path('neighborhood/point_of_interest/<int:pk>/images/',
         showPointOfInterestImages, name='showPointOfInterestImages'),
    path('neighborhood/<int:pk>/profile/', neighborhoodProfile, name='neighborhoodProfile'),
    path('point_of_interest/<int:pk>/profile/', pointOfInterestProfile, name='pointOfInterestProfile'),
]

neighborhood/models.py
from cloudinary.models import CloudinaryField
from django.contrib.gis.db import models
from registration.models import Neighborhood


class NeighborhoodImage(models.Model):
    image = CloudinaryField('image')
    neighborhood = models.ForeignKey(Neighborhood, on_delete=models.CASCADE, db_constraint=False, null=True)
    description = models.TextField(default='')

    class Meta:
        db_table = 'neighborhood_image'

    def __str__(self):
        return self.neighborhood.name + ' | ' + self.description


class PointOfInterest(models.Model):
    name = models.CharField(max_length=45)
    location = models.PointField()
    description = models.TextField(default='')

    class Meta:
        db_table = 'point_of_interest'

    def __str__(self):
        return self.name


class PointOfInterestImage(models.Model):
    image = CloudinaryField('image')
    point_of_interest = models.ForeignKey(PointOfInterest, on_delete=models.CASCADE, db_constraint=False, null=True)
    description = models.TextField(default='')

    class Meta:
        db_table = 'point_of_interest_image'

    def __str__(self):
        return self.point_of_interest.name + ' | ' + self.description


class NeighborhoodPointOfInterest(models.Model):
    neighborhood = models.ForeignKey(Neighborhood, on_delete=models.CASCADE, db_constraint=False, null=True)
    point_of_interest = models.ForeignKey(PointOfInterest, on_delete=models.CASCADE, db_constraint=False, null=True)

    class Meta:
        db_table = 'neighborhood_point_of_interest'

    def __str__(self):
        return self.neighborhood.name + ' | ' + self.point_of_interest.name


class PointOfInterestDTO:
    id = models.IntegerField()
    name = models.CharField(max_length=45)
    location = []
    description = models.TextField(default='')

neighborhood/forms.py
from django.forms import ModelForm

from neighborhood.models import (NeighborhoodImage, PointOfInterestImage)


class NeighborhoodImageForm(ModelForm):
    class Meta:
        model = NeighborhoodImage
        fields = ['image', 'description']


class PointOfInterestImageForm(ModelForm):
    class Meta:
        model = PointOfInterestImage
        fields = ['image', 'description']

neighborhood/views.py
import json

import cloudinary
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.contrib.gis.geos import GEOSGeometry

from neighborhood.forms import NeighborhoodImageForm, PointOfInterestImageForm
from neighborhood.models import NeighborhoodImage, PointOfInterest, NeighborhoodPointOfInterest, PointOfInterestImage
from registration.models import Neighborhood, UserNeighborhood


@login_required
def createNeighborhood(request):
    args = {}
    user_neighborhood = UserNeighborhood.objects.all().filter(user=request.user).first()
    neighborhood = Neighborhood.objects.get(pk=user_neighborhood.neighborhood.pk)
    args['name'] = neighborhood.name
    if request.method == 'POST':
        coords = request.POST.get('coordinates')
        final_coords = ""

        for xy in range(0, len(coords.split(',')), 2):
            final_coords = final_coords + coords.split(',')[xy] + ' ' + coords.split(',')[xy + 1] + ','

        final_coords = final_coords[:-1]
        neighborhood.name = request.POST.get('neighborhood-name')
        neighborhood.shape = GEOSGeometry('MULTIPOLYGON(((' + final_coords + ')))')
        neighborhood.is_active = True
        neighborhood.user = request.user
        neighborhood.description = request.POST.get('neighborhood-description')
        neighborhood.save()
        return HttpResponseRedirect('/')

    return render(request, 'create_neighborhood.html', args)


@login_required
def editNeighborhood(request):
    args = {}
    user_neighborhood = UserNeighborhood.objects.all().filter(user=request.user).first()
    neighborhood = Neighborhood.objects.get(pk=user_neighborhood.neighborhood.pk)
    shape = GEOSGeometry(neighborhood.shape)
    input_string = shape.geojson
    coordinates_data = json.loads(input_string)
    args['coordinates'] = coordinates_data['coordinates'][0][0]
    args['neighborhood'] = neighborhood

    if request.method == 'POST':
        coords = request.POST.get('coordinates')

        if coords == '':
            neighborhood.name = request.POST.get('neighborhood-name')
            neighborhood.description = request.POST.get('neighborhood-description')
        else:
            final_coords = ""

            for xy in range(0, len(coords.split(',')), 2):
                final_coords = final_coords + coords.split(',')[xy] + ' ' + coords.split(',')[xy + 1] + ','

            final_coords = final_coords[:-1]
            neighborhood.name = request.POST.get('neighborhood-name')
            neighborhood.shape = GEOSGeometry('MULTIPOLYGON(((' + final_coords + ')))')
            neighborhood.description = request.POST.get('neighborhood-description')

        neighborhood.save()

        return HttpResponseRedirect('/')

    return render(request, 'edit_neighborhood.html', args)


def showNeighborhoodImages(request):
    images = None
    user_neighborhood = UserNeighborhood.objects.all().filter(user=request.user).first()
    n = Neighborhood.objects.get(pk=user_neighborhood.neighborhood.pk)
    if n is not None:
        images = NeighborhoodImage.objects.all().filter(neighborhood=n)
    return render(request, 'neighborhood_images.html', {'images': images, 'neighborhood': n, })


def showPointOfInterestImages(request, pk):
    point_of_interest = PointOfInterest.objects.get(pk=pk)
    images = PointOfInterestImage.objects.all().filter(point_of_interest=point_of_interest)
    return render(request,
                  'point_of_interest_images.html', {'images': images, 'point': point_of_interest, })


@login_required
def uploadNeighborhoodImage(request, pk):
    context = dict(backend_form=NeighborhoodImageForm())

    if request.method == 'POST':
        desc = request.POST.get('image-description')
        archivo = request.FILES['image-file']

        n = Neighborhood.objects.get(pk=pk)
        neighborhood_image = NeighborhoodImage()
        neighborhood_image.neighborhood = n
        neighborhood_image.image = archivo
        neighborhood_image.description = desc
        neighborhood_image.save()

        return HttpResponseRedirect('/neighborhood/images/')

    return render(request, 'upload_neighborhood_image.html', context)


@login_required
def editNeighborhoodImage(request, pk):
    args = {}
    image = NeighborhoodImage.objects.get(pk=pk)
    args['image'] = image

    if request.method == 'POST':
        image.description = request.POST.get('image-description')
        image.save()

        return HttpResponseRedirect('/neighborhood/images/')

    return render(request, 'edit_neighborhood_image.html', args)


@login_required
def deleteNeighborhoodImage(request, pk):
    image = NeighborhoodImage.objects.get(pk=pk)
    image.delete()
    cloudinary.uploader.destroy(image.image.public_id, invalidate=True)
    return HttpResponseRedirect('/neighborhood/images/')


@login_required
def addPointOfInterest(request, pk):
    args = {}
    neighborhood = Neighborhood.objects.get(pk=pk)
    shape = GEOSGeometry(neighborhood.shape)
    input_string = shape.geojson
    coordinates_data = json.loads(input_string)
    args['coordinates'] = coordinates_data['coordinates'][0][0]

    if request.method == 'POST':
        point = request.POST.get('point').split(',')

        point_of_interest = PointOfInterest()
        point_of_interest.name = request.POST.get('point-name')
        point_of_interest.description = request.POST.get('point-description')
        point_of_interest.location = GEOSGeometry('POINT(' + point[0] + ' ' + point[1] + ')')
        point_of_interest.save()

        neighborhood_point_of_interest = NeighborhoodPointOfInterest()
        neighborhood_point_of_interest.neighborhood = neighborhood
        neighborhood_point_of_interest.point_of_interest = point_of_interest
        neighborhood_point_of_interest.save()

        return HttpResponseRedirect('/neighborhood/points_of_interest/')

    return render(request, 'add_point_of_interest.html', args)


@login_required
def editPointOfInterest(request, pk):
    args = {}
    point_of_interest = PointOfInterest.objects.get(pk=pk)
    location = GEOSGeometry(point_of_interest.location)
    input_string = location.geojson
    coordinates_data = json.loads(input_string)
    args['coordinates'] = coordinates_data['coordinates']
    args['point'] = point_of_interest

    user_neighborhood = UserNeighborhood.objects.all().filter(user=request.user).first()
    neighborhood = Neighborhood.objects.get(pk=user_neighborhood.neighborhood.pk)
    shape = GEOSGeometry(neighborhood.shape)
    input_string_shape = shape.geojson
    coordinates_data_neighborhood = json.loads(input_string_shape)
    args['coordinates_neighborhood'] = coordinates_data_neighborhood['coordinates'][0][0]

    if request.method == 'POST':
        coords = request.POST.get('point')
        if coords == '':
            point_of_interest.name = request.POST.get('point-name')
            point_of_interest.description = request.POST.get('point-description')
        else:
            point_of_interest.name = request.POST.get('point-name')
            point_of_interest.description = request.POST.get('point-description')
            point = request.POST.get('point').split(',')
            point_of_interest.location = GEOSGeometry('POINT(' + point[0] + ' ' + point[1] + ')')
        point_of_interest.save()

        return HttpResponseRedirect('/neighborhood/points_of_interest/')

    return render(request, 'edit_point_of_interest.html', args)


def showPointsOfInterest(request):
    points_of_interest = None
    user_neighborhood = UserNeighborhood.objects.all().filter(user=request.user).first()
    n = Neighborhood.objects.get(pk=user_neighborhood.neighborhood.pk)
    if n is not None:
        points_of_interest = NeighborhoodPointOfInterest.objects.all().filter(neighborhood=n)
    return render(request, 'neighborhood_points_of_interest.html',
                  {'points': points_of_interest, 'neighborhood': n, })


@login_required
def deletePointOfInterest(request, pk):
    point_of_interest = PointOfInterest.objects.get(pk=pk)

    images = PointOfInterestImage.objects.all().filter(point_of_interest=point_of_interest)
    for image in images:
        cloudinary.uploader.destroy(image.image.public_id, invalidate=True)

    point_of_interest.delete()
    return HttpResponseRedirect('/neighborhood/points_of_interest/')


@login_required
def deletePointOfInterestImage(request, pk):
    image = PointOfInterestImage.objects.get(pk=pk)
    point_of_interest = image.point_of_interest
    image.delete()
    cloudinary.uploader.destroy(image.image.public_id, invalidate=True)
    images = PointOfInterestImage.objects.all().filter(point_of_interest=point_of_interest)
    return render(request,
                  'point_of_interest_images.html', {'images': images, 'point': point_of_interest, })


@login_required
def uploadPointOfInterestImage(request, pk):
    args = {}
    context = dict(backend_form=PointOfInterestImageForm())
    args['context'] = context
    args['pk'] = str(pk)

    if request.method == 'POST':
        desc = request.POST.get('image-description')
        image = request.FILES['image-file']

        point_of_interest = PointOfInterest.objects.get(pk=pk)

        point_of_interest_image = PointOfInterestImage()
        point_of_interest_image.point_of_interest = point_of_interest
        point_of_interest_image.image = image
        point_of_interest_image.description = desc
        point_of_interest_image.save()

        return HttpResponseRedirect("/neighborhood/point_of_interest/" + str(pk) + "/images/")

    return render(request, 'upload_point_of_interest_image.html', args)


@login_required
def editPointOfInterestImage(request, pk):
    args = {}
    image = PointOfInterestImage.objects.get(pk=pk)
    point_of_interest = image.point_of_interest
    args['image'] = image
    args['point'] = point_of_interest

    if request.method == 'POST':

neighborhood/templates/add_point_of_interest.html
{% extends 'base.html' %}
{% load static %}
{% load cloudinary %}
{% block content %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="initial-scale=1,maximum-scale=1,user-scalable=no">
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.js"></script>
    <style>
          #map {
         margin-right: auto;
         margin-left: auto;
         position: relative;
        height: inherit;
        width: inherit;
         }

         #map-container {
        height: 780px;
        width: 100%;
        left:2px;
         right:2px;
        margin-right: auto;
         margin-left: auto;
    }

         p {
         font-family: 'Open Sans';
         margin: 0;
         font-size: 13px;
         }

         #boton {
         height: 75px;
         width: 150px;
         position: absolute;
         bottom: 40px;
         left: 10px;
         background-color: rgba(255, 255, 255, 0.9);
         padding: 15px;
         text-align: center;
         }
         p {
         font-family: 'Open Sans';
         margin: 0;
         font-size: 13px;
         }
         #point-name:focus{
    box-shadow: 0 0 0 0.25rem black;
    border: black;
    }
      #point-description:focus{
    box-shadow: 0 0 0 0.25rem black;
    border: black;
    }


    </style>
</head>
<body>
<script src="https://unpkg.com/@turf/turf@6/turf.min.js"></script>
<script src="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-draw/v1.2.2/mapbox-gl-draw.js"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/magnific-popup.min.css" rel="stylesheet" />
<link rel="stylesheet" href="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-draw/v1.2.2/mapbox-gl-draw.css" type="text/css">
<link rel="stylesheet" href="{% static '/css/modal.css' %}">
<div class="modal modal-signin position-static d-block py-5" tabindex="-1" role="dialog" id="modalSignin" style="background-color: #036749; width:100%;align-items:center;" >
    <div style="width: 90%; margin-right: auto;
         margin-left: auto;">
        <div class="modal-content rounded-5 shadow" >
            <div class="modal-header p-5 pb-4 border-bottom-0">
                <h2 class="fw-bold mb-0">Punto de interés</h2>
                <a href="/neighborhood/points_of_interest/">
                    <button id="btn-close" type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </a>
            </div>
            <div class="modal-body p-5 pt-0">
                <form method="post" action="" enctype="multipart/form-data">
                    {% csrf_token %}

                    <div class="form-floating mb-3">
                        <input type="text" class="form-control rounded-4" id="point-name" placeholder="Nombre" name="point-name" required>
                        <label for="point-name">Nombre</label>
                    </div>

                    <div class="form-floating mb-3">
                        <textarea type="textarea" class="form-control rounded-4" id="point-description"
                                  placeholder="Descripción" name="point-description"
                                  style="height: 150px; resize: none; text-indent: 0;" required></textarea>
                        <label for="point-description">Descripción</label>
                    </div>

                    <input type="hidden" id="point" name="point" value="">
                    <div id="map-container"><div id="map"></div></div>
                    <br>
                    <button id="btn-login" class="w-100 mb-2 btn btn-lg rounded-4" type="submit">Guardar</button>
                </form>
            </div>
            <div>
            </div>
        </div>
    </div>
</div>
<script>
     mapboxgl.accessToken = 'pk.eyJ1IjoibGx1bGxtYXJpYXNvbCIsImEiOiJjbDFteGZ5YnowMzRuM2RvNTVjYXNoOXJqIn0.T0K0fWkWlBEsqTDKXw6Qyw';
     var labels = [
    {% for c in coordinates %}
      {{ c }},
    {% endfor %}
  ]
     const map = new mapboxgl.Map({
            container: 'map',
            style: 'mapbox://styles/mapbox/streets-v11',
            center: [-61.49174078974892, -31.252666415093373],
            zoom: 12
            });

    const draw = new MapboxDraw({
        displayControlsDefault: false,
        controls: {
        point: true,
        trash: true
        },
        defaultMode: 'draw_point'
        },
    );

    map.addControl(draw);
    map.on('draw.create', updateArea);
    map.on('draw.delete', updateAreaWhenDeleting);
    map.on('draw.update', updateArea);

    function inside(point, vs) {
        var x = point[0], y = point[1];

        var inside = false;
        for (var i = 0, j = vs.length - 1; i < vs.length; j = i++) {
            var xi = vs[i][0], yi = vs[i][1];
            var xj = vs[j][0], yj = vs[j][1];

            var intersect = ((yi > y) != (yj > y))
                && (x < (xj - xi) * (y - yi) / (yj - yi) + xi);
            if (intersect) inside = !inside;
        }

        return inside;
    };

    function updateArea(e) {
        const data = draw.getAll();
        const coordinates = data['features'][data.features.length - 1]['geometry']['coordinates'];
        document.getElementById('point').value = coordinates;

        if (data.features.length > 1) {
            alert("Debes selecccionar un solo punto.");
            document.querySelector('#btn-login').disabled = true;
        } else {
             document.querySelector('#btn-login').disabled = false;
        }

        var polygon = labels;
        console.log(inside(coordinates, polygon));

        if (inside(coordinates, polygon) == false) {
            alert("El punto de interés debe estar dentro del área del barrio.");
            document.querySelector('#btn-login').disabled = true;
        } else {
          document.querySelector('#btn-login').disabled = false;
        }

        if (data.features.length == 0) {
            document.querySelector('#btn-login').disabled = true;
        }
    }

    function updateAreaWhenDeleting(e) {
        const data = draw.getAll();

        if (data['features'].length == 0) {
            document.querySelector('#btn-login').disabled = true;
            return;
        }

        const coordinates = data['features'][0]['geometry']['coordinates'];
        document.getElementById('point').value = coordinates;

        if (data.features.length > 1) {
            alert("Debes selecccionar un solo punto.");
            document.querySelector('#btn-login').disabled = true;
        } else {
             document.querySelector('#btn-login').disabled = false;
             updateArea(e);
        }
    }

    map.on('load', () => {
        document.querySelector('#btn-login').disabled = true;
        map.addSource('national-park', {
        'type': 'geojson',
        'data': {
        'type': 'FeatureCollection',
        'features': [
        {
        'type': 'Feature',
        'geometry': {
        'type': 'Polygon',
        'coordinates': [
        labels
        ]
        }
        },
        {
        'type': 'Feature',
        'geometry': {
        'type': 'Point',
        'coordinates': [-121.415061, 40.506229]
        }
        },
        {
        'type': 'Feature',
        'geometry': {
        'type': 'Point',
        'coordinates': [-121.505184, 40.488084]
        }
        },
        {
        'type': 'Feature',
        'geometry': {
        'type': 'Point',
        'coordinates': [-121.354465, 40.488737]
        }
        }
        ]
        }
        });

        map.addLayer({
        'id': 'park-boundary',
        'type': 'fill',
        'source': 'national-park',
        'paint': {
        'fill-color': '#036749',
        'fill-opacity': 0.4
        },
        'filter': ['==', '$type', 'Polygon']
        });

        map.addLayer({
        'id': 'park-volcanoes',
        'type': 'circle',
        'source': 'national-park',
        'paint': {
        'circle-radius': 6,
        'circle-color': '#B42222'
        },
        'filter': ['==', '$type', 'Point']
        });
        });

</script>
</body>
{% endblock content %}

neighborhood/templates/edit_neighborhood_image.html
{% extends 'base.html' %}
{% load static %}
{% load cloudinary %}
{% cloudinary photo.image format="jpg" width=120 height=80 crop="fill" %}
{% block content %}
<style>
    #image-description:focus{
    box-shadow: 0 0 0 0.25rem black;
    border: black;
    }

    .holder img {
    width:90px;
   height:90px;
   object-fit:scale-down;
  }
</style>
<link rel="stylesheet" href="{% static '/css/modal.css' %}"></head>
<div class="modal modal-signin position-static d-block py-5" tabindex="-1" role="dialog" id="modalSignin" style="background-color: #036749; width:100%;align-items:center;" >
  <div style="width: 90%; margin-right: auto;
         margin-left: auto;">
    <div class="modal-content rounded-5 shadow" >
      <div class="modal-header p-5 pb-4 border-bottom-0">
        <h2 class="fw-bold mb-0">Editar</h2>
        <a href="/neighborhood/images/">
          <button id="btn-close" type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </a>
      </div>
      <div class="modal-body p-5 pt-0" style="text-align:left">
        <form action="" method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="holder">
            <img class="d-block w-100" src="{{ image.image.url }}" alt="Imagen">
          </div>
          <br>
          <div class="form-floating mb-3">
            <textarea type="textarea" class="form-control rounded-4" id="image-description"
                      placeholder="Descripción" name="image-description"
                      style="height: 150px; resize: none; text-indent: 0;">{{ image.description }}</textarea>
            <label for="image-description">Descripción</label>
          </div>
          <button id="btn-login" class="w-100 mb-2 btn btn-lg rounded-4" type="submit">Guardar</button>
        </form>
      </div>
      <div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

neighborhood/templates/edit_point_of_interest_image.html
{% extends 'base.html' %}
{% load static %}
{% load cloudinary %}
{% cloudinary photo.image format="jpg" width=120 height=80 crop="fill" %}
{% block content %}
<style>
    #image-description:focus{
    box-shadow: 0 0 0 0.25rem black;
    border: black;
    }

    .holder img {
    width:90px;
   height:90px;
   object-fit:scale-down;
  }
</style>
<link rel="stylesheet" href="{% static '/css/modal.css' %}"></head>
<div class="modal modal-signin position-static d-block py-5" tabindex="-1" role="dialog" id="modalSignin" style="background-color: #036749; width:100%;align-items:center;" >
  <div style="width: 90%; margin-right: auto;
         margin-left: auto;">
    <div class="modal-content rounded-5 shadow" >
      <div class="modal-header p-5 pb-4 border-bottom-0">
        <h2 class="fw-bold mb-0">Editar</h2>
        <a href="/neighborhood/point_of_interest/{{point.pk}}/images/">
          <button id="btn-close" type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </a>
      </div>
      <div class="modal-body p-5 pt-0" style="text-align:left">
        <form action="" method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="holder">
            <img class="d-block w-100" src="{{ image.image.url }}" alt="Imagen">
          </div>
          <br>
          <div class="form-floating mb-3">
            <textarea type="textarea" class="form-control rounded-4" id="image-description"
                      placeholder="Descripción" name="image-description"
                      style="height: 150px; resize: none; text-indent: 0;">{{ image.description }}</textarea>
            <label for="image-description">Descripción</label>
          </div>
          <button id="btn-login" class="w-100 mb-2 btn btn-lg rounded-4" type="submit">Guardar</button>
        </form>
      </div>
      <div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

neighborhood/templates/neighborhood_list.html
{% block list %}
<br>
<h3 class="fw-bold mb-0" style="color:white;">Barrios</h3>
<br>
<div class="table-responsive" style="background:white;">
    <table class="table table-hover light" id="images-table">
        <tbody>
        {% for n in neighborhoods %}
        <tr>
            <td>
                <a href="/neighborhood/{{n.pk}}/profile/" style="text-decoration:none; color:black;">
                    {{ n.name }}
                    {% if n.pk == neighborhood.neighborhood.pk %}
                        <small><strong>(tu barrio)</strong></small>
                    {% endif %}
                </a>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock list %}

neighborhood/templates/points_of_interests_buttons.html
<div style="width:100%; margin:0px;">
  {% for point in points %}
  <a href="{% url 'neighborhood:pointOfInterestProfile' point.pk %}">
    <button id="btn-login"
            class="w-100 mb-2 btn btn-lg rounded-4"
            style="height:40px !important; font-size:16px !important; margin-top:5px;">
      <small>{{ point.name }}</small>
    </button>
  </a>
  {% endfor %}
</div>

neighborhood/templates/upload_neighborhood_photo.html
{% extends 'base.html' %}
{% load static %}
{% load cloudinary %}
{% cloudinary photo.image format="jpg" width=120 height=80 crop="fill" %}
{% block content %}
<br>
<h1>Foto</h1>
</span>
<br>
<div>
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ backend_form }}
        <input type="submit" value="Agregar foto">
        <a href="/neighborhood/photos/" class="btn btn-default">Cancelar</a>
    </form>
</div>
{% endblock content %}