chat/urls.py
from django.urls import path
from .views import (
    chat,
)

app_name = 'chat'
urlpatterns = [
    path('', chat, name='chat'),
]

conocemibarrio/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from conocemibarrio import settings
from registration.views import send_push
from forum.views import notifications

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('registration.urls')),
    path('', include('neighborhood.urls')),
    path('forum/', include('forum.urls')),
    path('notifications/', notifications, name='notifications'),
    path('', include('pwa.urls')),
    path('', include('profile.urls')),
    path('chat/', include('chat.urls')),
    path('send_push', send_push),
    path('webpush/', include('webpush.urls')),
    path('sw.js', TemplateView.as_view(template_name='sw.js', content_type='application/x-javascript')),
    path('', include('realtime_map.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

forum/urls.py
from django.urls import path
from django.views.generic import TemplateView

from registration.views import send_push
from .views import (
    addPost,
    posts,
    postDetail,
    deletePost,
    likeComment,
    deleteComment,
    reportComment,
)

app_name = 'forum'

urlpatterns = [
    path('', posts, name='posts'),
    path('new-topic/', addPost, name='addPost'),
    path('topic/<int:pk>/', postDetail, name='postDetail'),
    path('topic/<int:pk>/sw.js', TemplateView.as_view(template_name='sw.js', content_type='application/x-javascript')),
    path('topic/<int:pk>/delete/', deletePost, name='deletePost'),
    path('like-comment/<int:pk>/', likeComment, name='likeComment'),
    path('comment/<int:pk>/delete/', deleteComment, name='deleteComment'),
    path('report-comment/<int:pk>/', reportComment, name='reportComment'),
    path('sw.js', TemplateView.as_view(template_name='sw.js', content_type='application/x-javascript')),
    path('manifest.json', TemplateView.as_view(template_name='manifest.json', content_type='application/json')),
    path('send_push', send_push),
]

registration/urls.py
from django.urls import path, reverse_lazy, include
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

from .views import (registration,
                    activation,
                    logIn,
                    home,
                    logOut,
                    joinNeighborhood,
                    registrationNeighborhoodAdmin,
                    administrationRequests,
                    approveAdministrationRequest,
                    rejectAdministrationRequest,
                    about)

app_name = 'registration'

urlpatterns = [
    path('', home, name='home'),
    path('registration/', registration, name='registration'),
    path('registration/neighborhood/admin/', registrationNeighborhoodAdmin, name='registrationNeighborhoodAdmin'),
    path('activation/<uidb64>/<token>/', activation, name='activation'),
    path('login/', logIn, name='logIn'),
    path('logout/', logOut, name='logOut'),
    path('password_reset/',
         auth_views.PasswordResetView.as_view(
             template_name='password_reset_form.html',
             email_template_name='password_reset_email.html',
             success_url=reverse_lazy('registration:password_reset_done')),
         name='password_reset'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='password_reset_confirm.html',
             success_url=reverse_lazy('registration:password_reset_complete')),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='password_reset_complete.html'),
         name='password_reset_complete'),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('social-auth/', include('social_django.urls', namespace="social")),
    path('location/', registration, name='registration'),
    path('join_neighborhood/', joinNeighborhood, name='joinNeighborhood'),
    path('administration/requests/', administrationRequests, name='administrationRequests'),
    path('administration/request/<int:pk>/approve/', approveAdministrationRequest, name='approveAdministrationRequest'),
    path('administration/request/<int:pk>/reject/', rejectAdministrationRequest, name='rejectAdministrationRequest'),
    path('about/', about, name='about'),
]

forum/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField

from registration.models import Neighborhood


class Post(models.Model):
    title = models.CharField(max_length=30)
    body = RichTextField(blank=True, null=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    neighborhood = models.ForeignKey(Neighborhood, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.title + ' | ' + str(self.author)


class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    content = models.CharField(max_length=500)
    creationDate = models.DateTimeField(auto_now_add=True)
    liked = models.BooleanField(default=False)
    likes = models.ManyToManyField(User, related_name='forum_answers')
    complaints = models.ManyToManyField(User, related_name='complaints')
    removed = models.BooleanField(default=False)

    def __str__(self):
        return self.content

    def total_likes(self):
        return self.likes.count()

    def total_complaints(self):
        return self.complaints.all().count()


class Complaint(models.Model):
    REASONS = (
        (1, 'Contenido discriminativo'),
        (2, 'Comentario violento'),
        (3, 'Comentario de amenaza'),
        (4, 'Contenido irrespetuoso'),
        (5, 'Otro'),
    )
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, related_name='reported_comment')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_who_reports')
    reason = models.CharField(choices=REASONS, default=1, max_length=30)


class Notification(models.Model):
    body = models.CharField(max_length=100)
    recipient = models.ForeignKey(User, on_delete=models.CASCADE)
    creationDate = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'notification'

forum/forms.py
from django import forms
from .models import (
    Post,
    Comment,
    Complaint,
)


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'body']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']


class ComplaintForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ComplaintForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Complaint
        fields = ['reason']

forum/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Count
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render, get_object_or_404
from django.urls import reverse

from registration.models import UserNeighborhood
from .models import (
    Post,
    Comment,
    Complaint, Notification,
)
from .forms import (
    PostForm,
    CommentForm,
    ComplaintForm,
)


@login_required
def posts(request):
    try:
        user_neighborhood = UserNeighborhood.objects.get(user=request.user)
    except UserNeighborhood.DoesNotExist:
        return render(
            request,
            'join_a_neighborhood.html',
            {'function': "foro"}
        )
    post_list = Post.objects.all().filter(neighborhood=user_neighborhood.neighborhood)
    n = user_neighborhood.neighborhood.name
    return render(request, 'posts.html', {'posts': post_list, 'neighborhood': n})


@login_required
def addPost(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            user_neighborhood = UserNeighborhood.objects.all().filter(user=request.user).first()
            forum_post = form.save(commit=False)
            forum_post.author = request.user
            forum_post.neighborhood = user_neighborhood.neighborhood
            forum_post.save()
            return redirect('forum:posts')
    else:
        form = PostForm()
    return render(request, 'form.html', {'form': form})


@login_required
def postDetail(request, pk):
    post = Post.objects.get(pk=pk)
    author_user_id = post.author.pk
    comments = Comment.objects.filter(post=post).annotate(like_count=Count('likes')).order_by('-like_count')
    if request.method == "POST":
        form = CommentForm(data=request.POST)
        for field in form:
            print("Field Error:", field.name,  field.errors)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.author = request.user
            comment.save()
    else:
        form = CommentForm()

    for comment in comments:
        comment.total = comment.likes.count()
        if comment.likes.filter(id=request.user.id).exists():
            comment.liked = True

    user_complaints = Complaint.objects.filter(user=request.user)

    reported_comments = []
    for complaint in user_complaints:
        comment = complaint.comment
        reported_comments.append(comment)

    return render(
        request,
        'detail.html',
        {
            'post': post,
            'form': form,
            'comments': comments,
            'complaints': reported_comments,
            'author_user_id': author_user_id,
        }
    )


@login_required
def deletePost(request, pk):
    post = Post.objects.get(pk=pk)
    post.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def likeComment(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    if comment.likes.filter(id=request.user.id).exists():
        comment.likes.remove(request.user)
    else:
        comment.likes.add(request.user)
    return HttpResponseRedirect(reverse('forum:postDetail', args=[str(comment.post.id)]))


@login_required
def deleteComment(request, pk):
    comment = Comment.objects.get(pk=pk)
    comment.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def reportComment(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    if request.method == 'POST':
        form = ComplaintForm(data=request.POST)
        complaint = Complaint()
        if form.is_valid:
            comment.complaints.add(request.user)
            if comment.total_complaints() > 4:
                comment.removed = True
            complaint.comment = comment
            complaint.user = request.user
            complaint.save()
            return HttpResponseRedirect(reverse('forum:postDetail', args=[str(comment.post.id)]))
    else:
        form = ComplaintForm()
    return render(
        request,
        'report.html',
        {
            'form': form,
            'comment': comment,
        },
    )


def notifications(request):
    notifications_list = Notification.objects.filter(recipient=request.user).order_by('creationDate').reverse()
    return render(request, 'notification_list.html', {'notifications': notifications_list})

forum/templates/comments.html
{% load static %}
<style>
    .comment-form {
        width: 100%;

        margin: auto;
    }
    .btn-primary {
        color: #079748;
        background-color: #fff;
        border-color: #079748;
    }
    .btn-primary:hover {
        color: #fff;
        background-color: #d4bd22;
        border-color: #fff;}

    .comment {
        width: 100%;

        padding: 15px;
        margin: auto;
    }
     .left, .right{
      float:right;
     }
     .wrap{
     width:100%;
     }

         .btn-outline-dark {
          color: black;
          border-color: white;
          background-color: white;
        }
        .btn-outline-dark:hover {
          color: white;
          background-color: black;
          border-color: black;
        }
</style>
{% for comment in comments %}
    {% if comment.removed == False %}
    <div class="modal modal-signin position-static d-block py-4" tabindex="-1" role="dialog" id="modalSignin" style="background-color: #036749; width:100%;" >
        <div style="width: 90%; margin-right: auto; margin-left: auto;">
            <div class="modal-content rounded-5 shadow" >
                <div class="modal-body p-7 pt-7">
                    {% if comment.author == request.user %}
                    <div>
                        <div class="text-left" style="display: inline-block; float:left;">
                            <small style="font-size:8px;">El {{ comment.creationDate }}</small>
                            <small style="font-size:8px;">
                                <strong>usted</strong> comentó:
                            </small>
                        </div>
                        <div class="text-right" style="display: inline-block; float:right;">
                            <a href="{% url 'forum:deleteComment' comment.pk %}"class="badge badge-danger"
                               onClick="return confirm('¿Seguro que quieres borrar tu respuesta?');" style="background-color:#dc3545; width: 60px;font-size:8px;">
                                <strong>Eliminar</strong>
                            </a>
                        </div>
                    </div>
                    {% endif %}
                    {% if comment.author != user and comment not in complaints %}
                    <div>
                        <div class="text-left" style="display: inline-block; float:left;">
                            <small style="font-size:8px;">El {{ comment.creationDate }}</small>
                            {% if comment.author == request.user %}
                            <small style="font-size:8px;">
                                <strong>usted</strong> comentó:
                            </small>
                            {% else %}
                            <small style="font-size:8px;">
                                <strong>{{ comment.author }}</strong> comentó:
                            </small>
                            {% endif %}
                        </div>
                        <div class="text-right" style="display: inline-block; float:right;">
                                <a class="badge rounded-pill bg-dark" href="{% url 'forum:reportComment' comment.pk %}" style="width: 60px;font-size:8px;">Denunciar</a>
                        </div>
                    </div>
                    <br>
                    {% endif %}
                    <br>
                    <q style="text-align:left">{{ comment.content }}</q>

                    <div class="wrap">
                        <div class ="right">
                            <form action="{% url 'forum:likeComment' comment.pk %}" method="POST">
                                {% csrf_token %}
                                {% if comment.liked %}
                                <button type="submit", name="answer_id", value="{{ comment.id }}" class="btn btn-danger btn-sm">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-hand-thumbs-down-fill" viewBox="0 0 16 16">
                                        <path d="M6.956 14.534c.065.936.952 1.659 1.908 1.42l.261-.065a1.378 1.378 0 0 0 1.012-.965c.22-.816.533-2.512.062-4.51.136.02.285.037.443.051.713.065 1.669.071 2.516-.211.518-.173.994-.68 1.2-1.272a1.896 1.896 0 0 0-.234-1.734c.058-.118.103-.242.138-.362.077-.27.113-.568.113-.856 0-.29-.036-.586-.113-.857a2.094 2.094 0 0 0-.16-.403c.169-.387.107-.82-.003-1.149a3.162 3.162 0 0 0-.488-.9c.054-.153.076-.313.076-.465a1.86 1.86 0 0 0-.253-.912C13.1.757 12.437.28 11.5.28H8c-.605 0-1.07.08-1.466.217a4.823 4.823 0 0 0-.97.485l-.048.029c-.504.308-.999.61-2.068.723C2.682 1.815 2 2.434 2 3.279v4c0 .851.685 1.433 1.357 1.616.849.232 1.574.787 2.132 1.41.56.626.914 1.28 1.039 1.638.199.575.356 1.54.428 2.591z"/>
                                    </svg>
                                </button>
                                {% else %}
                                <button type="submit", name="answer_id", value="{{ comment.id }}" class="btn btn-success btn-sm">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-hand-thumbs-up-fill" viewBox="0 0 16 16">
                                        <path d="M6.956 1.745C7.021.81 7.908.087 8.864.325l.261.066c.463.116.874.456 1.012.965.22.816.533 2.511.062 4.51a9.84 9.84 0 0 1 .443-.051c.713-.065 1.669-.072 2.516.21.518.173.994.681 1.2 1.273.184.532.16 1.162-.234 1.733.058.119.103.242.138.363.077.27.113.567.113.856 0 .289-.036.586-.113.856-.039.135-.09.273-.16.404.169.387.107.819-.003 1.148a3.163 3.163 0 0 1-.488.901c.054.152.076.312.076.465 0 .305-.089.625-.253.912C13.1 15.522 12.437 16 11.5 16H8c-.605 0-1.07-.081-1.466-.218a4.82 4.82 0 0 1-.97-.484l-.048-.03c-.504-.307-.999-.609-2.068-.722C2.682 14.464 2 13.846 2 13V9c0-.85.685-1.432 1.357-1.615.849-.232 1.574-.787 2.132-1.41.56-.627.914-1.28 1.039-1.639.199-.575.356-1.539.428-2.59z"/>
                                    </svg>
                                </button>
                                {% endif %}
                            </form>
                        </div>
                        <div class ="left"><small>{{ comment.total_likes }} me gusta &nbsp;</small></div>
                    </div>

                </div>
            </div>
        </div>
    </div>
    {% endif %}
{% empty %}
    <strong style="color:white">Todavía no hay comentarios</strong>
{% endfor %}

<div class="modal modal-signin position-static d-block py-4" tabindex="-1" role="dialog" id="modalSignin" style="background-color: #036749; width:100%;" >
    <div style="width: 90%; margin-right: auto; margin-left: auto;">
        <input id="author" hidden value="{{ author_user_id }}">
        <div id="respond" class="comment-respond; text-center">
            <form method="post" id="form" class="comment-form">{% csrf_token %}
                <input class="form-control" required="" placeholder="Tu comentario" id="content" name="content">
                <br>
                <button class="btn btn-outline-dark" type="submit" style="width:100%;">Comentar</button>
            </form>
        </div>
    </div>
</div>

<script>
const pushForm = document.getElementById('form');
const author = document.getElementById('author');
const content = document.getElementById('content');

pushForm.addEventListener('submit', async function (e) {
    $("body").css("cursor", "progress");
    e.preventDefault();
    const input = this[0];
    const textarea = this[1];

    const head = "[conocemibarrio]";
    const body = '{{ request.user.username }} ' +  "ha comentado tu post";
    const id = author.value;
    const text = content.value;

    if (head && body && id) {
        const res = await fetch('/send_push', {
            method: 'POST',
            body: JSON.stringify({head, body, id}),
            headers: {
                'content-type': 'application/json'
            }
        });
    }

    $.ajax({
        type:'POST',
        url: "/forum/topic/" + {{ post.pk }} + "/",
        headers: { "X-CSRFToken": '{{csrf_token}}' },
        data: { csrfmiddlewaretoken: '{{ csrf_token }}', content: text  }
    });
    window.location.reload();
});
</script>

forum/templates/detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
<link rel="stylesheet" href="{% static '/css/modal.css' %}">
<br/>

<div class="modal modal-signin position-static d-block py-4" tabindex="-1" role="dialog" id="modalSignin" style="background-color: #036749; width:100%;" >
    <div style="width: 90%; margin-right: auto;
             margin-left: auto;">
        <div class="modal-content rounded-5 shadow" >
            <div class="modal-header p-7 border-bottom-0">
                <h3 class="fw-bold mb-0">
                    <a href="{% url 'forum:postDetail' post.pk %}" onmouseover="this.style.color='#036749'"
                       onMouseOut="this.style.color='black'" style="color:black;">{{ post.title }}</a>
                </h3>
            </div>
            <p style="font-size:9px; color:black;">Por <strong>{{ post.author }}</strong></p>
            <hr style="margin:8px 15px">
            <div class="modal-body p-7 pt-7">
                {{ post.body | safe }}
            </div>
        </div>
    </div>
</div>

{% include "comments.html" %}

{% endblock content %}

forum/templates/form.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static '/css/modal.css' %}">
<br>
<div class="modal modal-signin position-static d-block py-4" tabindex="-1" role="dialog" id="modalSignin" style="background-color: #036749; width:100%;align-items:center;" >
    <div style="width: 90%; margin-right: auto;
             margin-left: auto;">
        <div class="modal-content rounded-5 shadow" >
            <div class="modal-header p-5 pb-4 border-bottom-0">
                <h4 class="fw-bold mb-0">
                    Nueva publicación
                </h4>
            </div>
            <div class="modal-body p-7 pt-0" style="padding: 30px; width: 100%;" align="center">
                <form method="POST" style="width:100%">
                    {% csrf_token %}
                    {{ form.media }}
                    <strong>
                        <label><p>Título</p></label>
                    </strong>
                    {{ form.title }}
                    <br>
                    {{ form.body }}
                    <br><br>
                    <button type="submit" class="btn btn-success">Guardar</button>
                    <a href="{% url 'forum:posts' %}"><button type="button" class="btn btn-light" >Cancelar</button></a>
                    <br>
                </form>
            </div>
        </div>
    </div>
</div>

<script>
    CKEDITOR.replace( 'body', {
     'toolbar':   [
	{ name: 'basicstyles', items: [ 'Bold', 'Italic', 'Underline','TextColor', 'BGColor'] }],
        'height': '100%',
        'width': '100%'
    })
</script>
{% endblock content %}

forum/templates/notification_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<br>
<h3 class="fw-bold mb-0" style="color:white;">Notificaciones</h3>
<br>
<div class="table-responsive" style="background:white;">
    <table class="table table-hover light" id="images-table">
        <tbody>
        {% for n in notifications %}
        <tr>
            <td style='text-align:left'>
                <small style="color:grey;font-size:9px;">
                    {{ n.creationDate }}
                </small> &nbsp;
                <a href="#" style="text-decoration:none; color:black;">
                    {{ n.body }}
                </a>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content %}

forum/templates/posts.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="{% static '/css/modal.css' %}">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

<style>
    .btn-primary {
        color: white;
        background-color: black;
        border-color: white;
        width:100%;
    }
    .btn-primary:hover {
        color: white;
        background-color: #036749;
        border-color: white;
    }
    h1, h2, h3 {
        color: white;
    }

    .btn-outline-dark {
          color: black;
          border-color: white;
          background-color: white;
        }
        .btn-outline-dark:hover {
          color: white;
          background-color: black;
          border-color: black;
        }
</style>

{% if args.error %}
    <br>
    <br>
    <button type="button" class="btn btn-info btn-lg" id="myBtn">Mostrar foros</button>
    <div class="modal fade" id="myModal" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Lo sentimos, no puedes ingresar</h4>
                </div>
                <div class="modal-body">
                    <p>{{ args.error }}</p>
                </div>
                <div class="modal-footer">
                    <a class="btn btn-primary" href="{% url 'registration:joinNeighborhood' %}" role="button">Unirme</a>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                </div>
            </div>

        </div>
    </div>
{% else %}

    {% if request.user.is_authenticated and user.is_superuser != 1 %}
    <div role="group" style="width:90%; margin:auto;">
        <h3>Foro de barrio {{ neighborhood }}</h3>
        <br>
        <a class="btn btn-outline-dark" href="{% url 'forum:addPost' %}" role="button" style="width:100%;">
            Publicar
        </a>
    </div>
    <br>
    {% for post in posts %}
    <div class="modal modal-signin position-static d-block py-4" tabindex="-1" role="dialog" id="modalSignin" style="background-color: #036749; width:100%;align-items:center;" >
        <div style="width: 90%; margin-right: auto;
             margin-left: auto;">
            <div class="modal-content rounded-5 shadow" >
                <div class="modal-header p-7 border-bottom-0">
                    <h4 class="fw-bold mb-0">
                        <a href="{% url 'forum:postDetail' post.pk %}" onmouseover="this.style.color='#036749'"
                       onMouseOut="this.style.color='black'" style="color:black;">{{ post.title }}</a>
                    </h4>

                </div>
                <p style="font-size:9px; color:black;">(Click para ver mas)</p>
                <hr style="margin:8px 15px">
                <div class="modal-body p-7 pt-7">
                    {% if post.author.username == request.user.username %}
                    <p class="mb-0" style="color:black;">Publicado por <strong>vos</strong></p>
                    <span style="text-align:right;">
                        <a href="{% url 'forum:deletePost' post.pk %}" class="badge badge-danger"
                           onClick="return confirm('¿Seguro que quieres borrar el tema del foro?');" style="background-color:#dc3545;">
                        <strong>Eliminar</strong>
                    </a>
                    </span>
                    {% else %}
                    <p class="mb-0" style="color:black;">Publicado por <strong>{{ post.author }}</strong></p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}

    {% endif %}
{% endif %}
{% endblock content %}

forum/templates/report.html
{% extends "base.html" %}
<script type="text/javascript" src="lib.js"></script>
{% block content %}
<style>
        .btn-outline-dark {
          color: black;
          border-color: white;
          background-color: white;
        }
        .btn-outline-dark:hover {
          color: white;
          background-color: black;
          border-color: black;
        }
</style>
<div class="text-center">
    <form action="" method="POST" class="post-form">{% csrf_token %}
        <br>
        <h4 style="color:white;">Elija un motivo de denuncia</h4>
        <br>
        {{ form.reason }}
        <br>
        <br>
        <a class="btn btn-outline-dark" role="button" value="Cancelar" href="{% url 'forum:postDetail' comment.post.pk %}">Cancelar</a>
        <button class="btn btn-danger btn-denunciar" type="submit" value="Denunciar">Denunciar</button>
        <br>
        <br>
    </form>
    {% endblock content %}
</div>