chat/urls.py
from django.urls import path
from .views import (
    chat,
)

app_name = 'chat'
urlpatterns = [
    path('', chat, name='chat'),
]

conocemibarrio/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from conocemibarrio import settings
from registration.views import send_push
from forum.views import notifications

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('registration.urls')),
    path('', include('neighborhood.urls')),
    path('forum/', include('forum.urls')),
    path('notifications/', notifications, name='notifications'),
    path('', include('pwa.urls')),
    path('', include('profile.urls')),
    path('chat/', include('chat.urls')),
    path('send_push', send_push),
    path('webpush/', include('webpush.urls')),
    path('sw.js', TemplateView.as_view(template_name='sw.js', content_type='application/x-javascript')),
    path('', include('realtime_map.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

forum/urls.py
from django.urls import path
from django.views.generic import TemplateView

from registration.views import send_push
from .views import (
    addPost,
    posts,
    postDetail,
    deletePost,
    likeComment,
    deleteComment,
    reportComment,
)

app_name = 'forum'

urlpatterns = [
    path('', posts, name='posts'),
    path('new-topic/', addPost, name='addPost'),
    path('topic/<int:pk>/', postDetail, name='postDetail'),
    path('topic/<int:pk>/sw.js', TemplateView.as_view(template_name='sw.js', content_type='application/x-javascript')),
    path('topic/<int:pk>/delete/', deletePost, name='deletePost'),
    path('like-comment/<int:pk>/', likeComment, name='likeComment'),
    path('comment/<int:pk>/delete/', deleteComment, name='deleteComment'),
    path('report-comment/<int:pk>/', reportComment, name='reportComment'),
    path('sw.js', TemplateView.as_view(template_name='sw.js', content_type='application/x-javascript')),
    path('manifest.json', TemplateView.as_view(template_name='manifest.json', content_type='application/json')),
    path('send_push', send_push),
]

profile/urls.py
from django.urls import path
from .views import profile

app_name = 'profile'

urlpatterns = [
    path('profile/', profile, name='users-profile'),
]

realtime_map/urls.py
from django.urls import path

from realtime_map.views import showRealTimeMap

app_name = 'realtime_map'

urlpatterns = [
    path('realtime_map/', showRealTimeMap, name='showRealTimeMap'),
]

registration/urls.py
from django.urls import path, reverse_lazy, include
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

from .views import (registration,
                    activation,
                    logIn,
                    home,
                    logOut,
                    joinNeighborhood,
                    registrationNeighborhoodAdmin,
                    administrationRequests,
                    approveAdministrationRequest,
                    rejectAdministrationRequest,
                    about)

app_name = 'registration'

urlpatterns = [
    path('', home, name='home'),
    path('registration/', registration, name='registration'),
    path('registration/neighborhood/admin/', registrationNeighborhoodAdmin, name='registrationNeighborhoodAdmin'),
    path('activation/<uidb64>/<token>/', activation, name='activation'),
    path('login/', logIn, name='logIn'),
    path('logout/', logOut, name='logOut'),
    path('password_reset/',
         auth_views.PasswordResetView.as_view(
             template_name='password_reset_form.html',
             email_template_name='password_reset_email.html',
             success_url=reverse_lazy('registration:password_reset_done')),
         name='password_reset'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='password_reset_confirm.html',
             success_url=reverse_lazy('registration:password_reset_complete')),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='password_reset_complete.html'),
         name='password_reset_complete'),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('social-auth/', include('social_django.urls', namespace="social")),
    path('location/', registration, name='registration'),
    path('join_neighborhood/', joinNeighborhood, name='joinNeighborhood'),
    path('administration/requests/', administrationRequests, name='administrationRequests'),
    path('administration/request/<int:pk>/approve/', approveAdministrationRequest, name='approveAdministrationRequest'),
    path('administration/request/<int:pk>/reject/', rejectAdministrationRequest, name='rejectAdministrationRequest'),
    path('about/', about, name='about'),
]

templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static '/css/modal.css' %}">
<div class="modal modal-signin position-static d-block py-5" tabindex="-1" role="dialog" id="modalSignin" style="background-color: #036749; width:100%;align-items:center;" >
    <div style="width: 90%; margin-right: auto; margin-left: auto;">
        <div class="modal-content rounded-5 shadow" >
            <div class="modal-header p-5 pb-4 border-bottom-0">
            </div>
            <div class="modal-body p-5 pt-0">
                <div>
                    <p style="text-align:justify;">
                        &nbsp;<strong style="font-size:18px;">CONOCE MI BARRIO</strong> es un proyecto desarrollado por estudiantes de la Carrera
                        Ingeniería en Informática (en el marco de la Cátedra Trabajo Final) de la Universidad Católica de
                        Santiago del Estero, Departamento Académico Rafaela.
                    </p>
                    <p style="text-align:justify;">
                        &nbsp;Si tenés dudas sobre el funcionamiento de la aplicación, podés acceder al <a href="https://sites.google.com/view/trabajofinal-ramirez-llull/manual-de-usuario">Manual de Usuario</a>.
                    </p>
                    <p style="text-align:justify;">
                        &nbsp;Si te interesa conocer en profundidad sobre el desarrollo del proyecto, podés acceder a la <a href="https://sites.google.com/view/trabajofinal-ramirez-llull/p%C3%A1gina-principal">Documentación</a>.
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en" translate="no">
{% load static %}
<head>
    <title>conocemibarrrio</title>
    <meta charset="utf-8">
    <link crossorigin="use-credentials" rel="manifest" href="manifest.json">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="vapid-key" content="{{ vapid_key }}">
    <meta name="google" content="notranslate">
    {% load pwa %}
    {% progressive_web_app_meta %}
    <script src="//code.jquery.com/jquery-1.10.2.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/headers/">
    <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static '/css/base.css' %}">
    <link rel="stylesheet" href="{% static '/css/modal.css' %}">
    <script src="{% static '/js/registerSw.js' %}"></script>
    {% block header %}
        {% include "header.html" %}
    {% endblock header %}
    {% block messages %}
        {% include "messages.html" %}
    {% endblock messages %}
    <style>
        .btn-outline-dark {
          color: black;
          border-color: white;
          background-color: white;
        }
        .btn-outline-dark:hover {
          color: white;
          background-color: black;
          border-color: black;
        }
        #btn-create-n, #btn-edit-n, #btn-imgs-n, #btn-points-n:focus{
         box-shadow: none;
        }
        tr.hover {
            cursor: pointer;
        }
    </style>

</head>
<body class="text-center" style="background-color: #036749; padding-bottom: 50px">
<main>
    {% if request.user.is_authenticated and user.groups.all.0.name == "neighborhood-admin"%}
        {% if request.path == '/' %}
    <br>
    <h3 class="fw-bold mb-0" style="color:white;">{{ n.name }}</h3>
    <br>
    <div role="group" style="width:80%; margin:auto;">
        {% if n.is_active == 0 %}
        <a href="/neighborhood/information/">
            <button id="btn-create-n" type="button" class="btn btn-outline-dark" style="width:100%;">
                Cargar información del barrio
            </button>
        </a>
        <br><br>
        {% else %}
        <a href="/neighborhood/information/edit/">
            <button id="btn-edit-n" type="button" class="btn btn-outline-dark" style="width:100%;">
            Editar información del barrio
            </button>
        </a>
        <br><br>
        {% endif %}
        <a href="/neighborhood/images/">
            <button id="btn-imgs-n" type="button" class="btn btn-outline-dark" style="width:100%;">
                Imágenes
            </button>
        </a>
        <br><br>
        <a href="/neighborhood/points_of_interest/">
            <button id="btn-points-n" type="button" class="btn btn-outline-dark" style="width:100%;">
                Puntos de interés
            </button>
        </a>

        <br><br>
        <a href="/administration/requests/">
            <button id="btn-create-n" type="button" class="btn btn-outline-dark" style="width:100%;">
                Solicitudes de administración del barrio
            </button>
        </a>

        <br><br>
        <a href="/forum/">
            <button id="btn-create-n" type="button" class="btn btn-outline-dark" style="width:100%;">
                Foro
            </button>
        </a>

    </div>
    {% endif %}
    {% else %}
    {% if request.user.is_authenticated and user.is_superuser == 0%}
    {% if neighborhood == null and request.path == '/' and user.groups.all.0.name != "neighborhood-admin" and request.path != '/forum/'%}
        <div role="group" style="width:80%; margin:auto;">
            <br>
            <a href="/join_neighborhood/">
                <button id="btn-create-n" type="button" class="btn btn-outline-dark" style="width:100%;">
                    Unirme a un barrio
                </button>
            </a>
            <br>
        </div>
    {% endif %}
    {% endif %}
    {% endif %}

    {% if request.user.is_authenticated and user.is_superuser == 1 %}
    {% if request.path == '/' %}
    <br>
    <div role="group" style="width:80%; margin:auto;">
        {% if n == null %}
        <a href="/administration/requests/">
            <button id="btn-create-n" type="button" class="btn btn-outline-dark" style="width:100%;">
                Solicitudes de administración de barrios
            </button>
        </a>
        <br><br>
        {% else %}
        <a href="/neighborhood/information/edit/">
            <button id="btn-edit-n" type="button" class="btn btn-outline-dark" style="width:100%;">
                Opción 2
            </button>
        </a>
        <br><br>
        {% endif %}
    </div>
    {% endif %}
    {% endif %}

    {% block content %}
    {% endblock content %}

    {% if not request.user.is_authenticated or request.user.is_authenticated and user.is_superuser != 1 and user.groups.all.0.name != "neighborhood-admin" %}
        {% if request.path == '/' %}
            {% block list %}
                {% include "neighborhood_list.html" %}
            {% endblock list %}
        {% endif %}
        {% block menu %}
            {% include "menu.html" %}
        {% endblock menu %}
    {% endif %}
</main>
<script src="{% static '/js/bootstrap.bundle.min.js' %}"></script>
<script>
        $('tr').click( function() {
    window.location = $(this).find('a').attr('href');
}).hover( function() {
    $(this).toggleClass('hover');
});
</script>
</body>
</html>

templates/header.html
{% load static %}
<div style="background-color: white">
    <header class="d-flex flex-wrap justify-content-around py-3 align-items-center">
        <div align="left" style="width:150px">
            <a href="/">
                <img src="{% static '/img/logo.png' %}" width="100%">
            </a>
        </div>
        <ul class="nav nav-pills">
            <li class="nav-item">
                <a href="/about/" class="nav-link active" style="color: #036749; background-color: white; width:100%">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-info-circle" viewBox="0 0 16 16">
                        <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                        <path d="m8.93 6.588-2.29.287-.082.38.45.083c.294.07.352.176.288.469l-.738 3.468c-.194.897.105 1.319.808 1.319.545 0 1.178-.252 1.465-.598l.088-.416c-.2.176-.492.246-.686.246-.275 0-.375-.193-.304-.533L8.93 6.588zM9 4.5a1 1 0 1 1-2 0 1 1 0 0 1 2 0z"/>
                    </svg>
                </a>
            </li>
        </ul>
        {% if 'login' in request.path %}
        <ul class="nav nav-pills">
            <li class="nav-item">
            </li>
        </ul>
        {% else %}
        {% if request.user.is_authenticated %}
        <ul class="nav nav-pills">
            <li class="nav-item">
                <a href="/notifications/" class="nav-link active" style="color: #036749; background-color: white; width:100%">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-bell-fill" viewBox="0 0 16 16">
                        <path d="M8 16a2 2 0 0 0 2-2H6a2 2 0 0 0 2 2zm.995-14.901a1 1 0 1 0-1.99 0A5.002 5.002 0 0 0 3 6c0 1.098-.5 6-2 7h14c-1.5-1-2-5.902-2-7 0-2.42-1.72-4.44-4.005-4.901z"/>
                    </svg>
                </a>
            </li>
        </ul>
        <ul class="nav nav-pills">
            <li class="nav-item">
                <a href="/logout/" class="nav-link active" style="background-color: #036749; width:100%">Salir</a>
            </li>
        </ul>
        {% else %}
        <ul class="nav nav-pills">
            <li class="nav-item">
                <a href="/login/" class="nav-link active" style="background-color: #036749; width:100%">Ingresar</a>
            </li>
        </ul>
        {% endif %}
        {% endif %}
    </header>
</div>

templates/join_a_neighborhood.html
{% extends "base.html" %}
{% block content %}
<div role="group" style="width:80%; margin:auto;">
    <br>
    <h2 class="text-center" style="color: whitesmoke">Para acceder al {{ function }} unite a tu barrio!</h2>
    <br>
    <a href="/join_neighborhood/">
        <button id="btn-create-n" type="button" class="btn btn-outline-dark" style="width:100%;">
            Unirme a un barrio
        </button>
    </a>
    <br>
</div>
{% endblock content %}

templates/menu.html
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
    nav {
        position: relative;
        width: 100%;
        height: 50px;
        background-color: white;
        font-size: 0;
    }
    nav a {
        line-height: 8%;
        height: 100%;
        font-size: 15px;
        display: inline-block;
        position: relative;
        z-index: 1;
        text-decoration: none;
        text-transform: uppercase;
        text-align: center;
        color: white;
        cursor: pointer;
    }

    a:nth-child(1) {
        width: 20%;
    }
    a:nth-child(2) {
        width: 20%;
    }
    a:nth-child(3) {
        width: 20%;
    }
    a:nth-child(4) {
        width: 20%;
    }
    a:nth-child(5) {
        width: 20%;
    }

    span {
        color: white;
    }

    footer {
        position: fixed;
        bottom: 0;
        width: 100%;
        height: 5%;
        color: white;
        top: 95%;
    }

    #footer-div {
        position: fixed;
        bottom: 0;
        width: 100%;
        height: 6%;
        background-color: white;
        top: 94%;
    }
</style>

<footer>
    <div id="footer-div"></div>
    <nav>
        <a href="{% url 'registration:home' %}"><img src="/static/img/home.png"
                                                     width="25"
                                                     height="25"></a>
        <a href="{% url 'forum:posts' %}"><img src="/static/img/forum.png"
                         width="25"
                         height="25"></a>
        <a href="{% url 'realtime_map:showRealTimeMap' %}"><img src="/static/img/location.png"
                         width="25"
                         height="25"></a>
        <a href="{% url 'chat:chat' %}"><img src="/static/img/chat.png"
                         width="25"
                         height="25"></a>
        <a href="{% url 'profile:users-profile' %}"><img src="/static/img/profile.png"
                         width="25"
                         height="25"></a>
    </nav>
</footer>

<script>
    $(document).ready(function(){
        $("#myBtn").click(function(){
            $("#myModal").modal();
        });
    });
</script>

templates/messages.html
{% for message in messages %}
<div class="alert {{ message.tags }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
</div>
{% endfor %}

templates/offline.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <br>
    <h2 style="color:white">Sin conexión a Internet</h2>
    <small style="color:white">Comprobá que tu dispositivo esté conectado a una red Wi-Fi o datos móviles.</small>
{% endblock content %}